<?= $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?= $this->headMeta() ?>
  <?= $this->headTitle() ?>

	<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="css/main_ie.css"/>
	<![endif]-->
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="/css/main.css" media="screen and (min-width: 700px)"/>
	<link rel="stylesheet" type="text/css" href="/css/main_mobile.css" media="screen and (max-width: 700px)"/>
	<link rel="stylesheet" type="text/css" href="/css/no_book.css" media="screen and (max-width: 950px)"/>
	<link rel="stylesheet" type="text/css" href="/css/book.css" media="screen and (min-width: 950px)"/>
	<link rel="stylesheet" type="text/css" href="/css/print.css" media="print"/>
  <?= $this->headLink() ?>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
	<script type="text/javascript" src="/js/main.js"></script>
  <?= $this->headScript() ?>
</head>
<body onload="loadCss()">
		<div class="main">
			<section class="mainSection">
<?= $this->layout()->content; ?>
      </section>
    </div>

<?= $this->partial('_book.phtml') ?>

      <div class="about" id="about">
			<div class="aboutLink" onclick="flipInner();">
				About
			</div>
			<div class="aboutInner" id="aboutInner">
				<p class="aboutText">Detta är gjort av David Eriksson och Christian Johannesson på Softhouse. Anpassat för användning i Chrome och Firefox </p>
			</div>
		</div>
		<div class="view noprint">
			<a href="#" onclick="mobile();" class="mobile">Mobile version</a>
			<a href="#" onclick="desktop();" class="desktop">Desktop version</a>
			</div>
      <div class="ieMain">
        <p>Hej,
        <br>
        Nu sitter du inte med en riktigt webläsare utan Internet Explorer, vi 
ber dig därför ladda hem en bra browser härifrån: <a 
href="http://www.google.co.jp/chrome/?hl=sv">Chrome</a> eller en helt OK browser 
härifrån: <a href="http://www.mozilla.org/sv-SE/firefox/new/">Firefox</a>
        <br>
        // 
        <br>
        Christian på Softhouse
        </p>
      </div>

<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-1802152-22']);
_gaq.push(['_trackPageview']);

(function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</body>
</html>
