<?php
$this->headLink()->appendStylesheet('/css/random.css', 'screen');
$this->headScript()->appendFile('/js/random.js');
?>
        <h3>Indiskt</h3>
				<form action="/order/add" method="POST">
					<div class="inputField">
						<label for="person">UID/e-postadress</label>
						<input type="text" id="person" name="person" placeholder="UID/e-postadress"/>
					</div>
					<div class="inputField">
						<label for="base_dish">Maträtt</label>
            <select id="base_dish" name="base_dish" class="tooltip" placeholder="Maträtt">
              <?php foreach ($this->dishes as $dish): ?>
                <option><?= $this->escape($dish) ?></option>
              <?php endforeach; ?>
            </select>
						<span class="toolTipContent" id="toolTipContent">Klicka på menysymbolen för detaljerad meny</span>
						<div class="meny" onclick="showMeny()" >
						<a class="tooltip" href="#"></a>
            </div>
            <div class="random" onclick="createStuffs()" title="Slumpa indisk maträtt">
            <a class="tooltip" href="#"></a>
            </div>
          </div>
					<div class="inputField">
						<label for="rice">Ris?</label>
						<input id="rice" name="rice" type="checkbox" value="1" checked="checked"/>
					</div>
					<div class="inputField">
						<label for="power">Styrka</label>
						<select id="power" name="power">
							<option value="svag">Svag</option>
							<option value="medium" selected>Medium</option>
							<option value="hot">Stark</option>
							<option value="xhot">Extra Stark</option>
						</select>
					</div>
					<div class="inputField">
						<label for="drink">Dryck</label>
						<select id="drink" name="drink">
							<option value="naturell">Mineralvatten Naturell</option>
							<option value="citrus">Mineralvatten Citrus</option>
							<option value="cola">Coca-Cola</option>
							<option value="cola zero">Coca-Cola Zero</option>
							<option value="fanta">Fanta</option>
							<option value="sprite">Sprite</option>
							<option value="pepsi">Pepsi</option>
						</select>
					</div>
					<div class="inputField">
						<label for="paid_to">Betalar till person</label>
						<select id="paid_to" name="paid_to">
              <option value="">(ingen)</option>
              <optgroup label="Snabbval">
              <option value="David">David</option>
              </optgroup>
<!--email_off-->
              <optgroup label="Alla">
              <?php foreach ($this->people as $person): ?>
              <option value="<?= $this->escape($person); ?>"><?= $this->escape($person); ?></option>
              <?php endforeach; ?>
              </optgroup>
<!--/email_off-->
            </select>
					</div>
					<div class="inputField order">
						<input name="add" type="submit" value="Lägg till beställning" class="orderButton">
          </div>

          <p class="note"><strong>Höjt pris april 2017!</strong> Alla rätter kostar <strong>70 kr</strong>.</p>

          <p class="note">Beställning ska göras innan klockan 10.15. Om du är 
sen, bekräfta med David innan du beställer.</p>

          <p class="note">OBS! Kontantbetalning till David endast mellan klockan 10.00 och 10.15.</p>

          <p class="note">Betala gärna via <a href="https://www.getswish.se/">Swish</a> genom att skicka pengar till 0768-832493.</p>

<p class="note">Är du med i <a href="http://eepurl.com/cALOZT">e-postlistan</a> ännu?</p>

					<a href="/order/summary" class="summary">Sammanställning</a>
        </form>

