<style>
.mainSection {
width:800px;
}
</style>
<h1>Indiskt <?= $this->today ?></h1>

<p>Totalt antal beställningar: <?= count($this->all); ?></p>

<h2>Personer som hämtar mat</h2>

<table>
<th>Person</th>
<th>Kontanter</th>
<th>Antal att betala för</th>
<?php foreach ($this->payAgentSummary as $entry): ?>
<tr>
<td><?= $entry->paid_to ?></td>
<td><?= $entry->paid_sum ?></td>
<td><?= $entry->count ?></td>
</tr>
<?php endforeach; ?>
<tr><td colspan="3"><hr/></td></tr>
<?php foreach ($this->unpaidSummary as $entry): ?>
<tr>
<td><?= $entry->person ?></td>
<td>&nbsp;</td>
<td>1</td>
</tr>
<?php endforeach; ?>
</table>



<h2>Matbeställning</h2>

<p>Telefonnummer: 0455-311002</p>

<table>
<?php foreach ($this->foodSummary as $entry): ?>
<tr>
<td><?= $entry->count ?></td>
<td><?= $entry->base_dish ?></td>
<td><?= $entry->power ?></td>
<td><?= $entry->rice ? 'Med ris' : 'Utan ris' ?></td>
</tr>
<?php endforeach; ?>
</table>

<h2>Dryck</h2>

<table>
<?php foreach ($this->drinkSummary as $entry): ?>
<tr>
<td><?= $entry->count ?></td>
<td><?= $entry->drink ?></td>
</tr>
<?php endforeach; ?>
</table>

<h2>Vem beställde vad?</h2>

<table>
<tr>
<th>Person</th>
<th>Maträtt</th>
<th>Styrka</th>
<th>Ris</th>
<th>Dryck</th>
<th>Betalar till</th>
</tr>

<?php foreach ($this->all as $entry): ?>
<tr>
<td class="summary-person"><a href="/order/show?person=<?= $this->escape($entry->person) ?>"><?= $this->escape($entry->person) ?></a></td>
<td class="summary-dish"><?= $entry->base_dish ?></td>
<td><?= $entry->power ?></td>
<td><?= $entry->rice ? '☑' : '☐' ?></td>
<td><?= $entry->drink ?></td>
<td>
<a href="/order/pay?<?= $this->escape($entry->person) ?>" title="Ändra betalning">
<?php if ($entry->paid_to && $entry->amount_paid && $entry->paid_to != $entry->person): ?>
<?= $entry->paid_to ?>
<?php else: ?>
(ingen)
<?php endif;?>
</a>
</td>
</tr>
<?php endforeach; ?>
</table>

<p>Sidan genererades klockan <?= strftime('%H:%M:%S'); ?></p>
